# docker-compose.yml
services:
  backend:
    build: ./backend
    container_name: video-player-backend
    # No ports needed here; Nginx will proxy to it
    volumes:
      - ./backend:/app
      - sqlite_db:/app/db
      - static_files:/app/staticfiles # Add this
    networks:
      - app-network
    # Use the new Gunicorn command from backend/Dockerfile
    # No need to override 'command' here if it's in the Dockerfile

  frontend:
    build: ./frontend
    container_name: video-player-frontend
    ports:
      - "80:80" # Use standard HTTP port 80
    volumes:
      - static_files:/app/staticfiles # Add this
      - ./webroot:/app/webroot
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  sqlite_db:
  static_files: # Define the shared volume
    driver: local

networks:
  app-network:
    driver: bridge